### ISSUE TITLE
retrieve-enrollment no longer includes the "id" 

### ISSUE THREAD

**Issue by david-raine** [akamai/cli-cps#65]
A recent update appears to have removed the "id" value in favour of a non-json message.
```
# akamai cps retrieve-enrollment --cn drtest3a.com.mands.uk --json
Getting details for drtest3a.com.mands.uk with enrollment-id: 208027
{
    "location": "/cps/v2/enrollments/208027",
    "ra": "lets-encrypt",
    "validationType": "dv",
```

This has two effects

1. The returned value is no longer valid json, even when the --json flag is used
2. The enrollment ID can no longer be found in the json part of the response

**Comment by mstojanowski** [comment]
Hi @david-raine ,

Thank you for raising this ticket. Unfortunately we can't reproduce your issue. Please find some ideas below that may help solve or clarity the issue:

1. Please ensure you use `akamai cps 2.0.0`.
2. Please execute you command again and confirm the issue is reproducible.
3. Please use `--yml` instead of `--json` and let as know if you experience the same problem.
4. Is this issue occur for this specific enrolment only or all the others as well?
5. Please redirect the output to the file to exclude a terminal issue.
6. Please let us know if this problematic enrolment contains any non-ASCII characters.

Please let us know about any new findings.


Regards,
Marcin
